inputs:
  python-version:
    description: "Python version to setup"
    required: false
    default: "3.9"

name: "Setup dependencies"
description: "Install all required dependencies for worflows to run."
runs:
  using: "composite"
  steps:
    - name: Install 3rd party dependencies
      run: sudo unblob/install-deps.sh
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Restore pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-${{ inputs.python-version }}

    - name: Pip install
      run: python -m pip install --upgrade pip poetry
      shell: bash

    - name: Restore poetry cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry/cache
          ~/.cache/pypoetry/artifacts
        key: poetry-cache-and-artifacts-${{ inputs.python-version }}

    - name: Restore virtualenvs
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: venv-${{ hashFiles('poetry.lock') }}-${{ inputs.python-version }}

    - name: Poetry install
      run: poetry install --with dev
      shell: bash
