name: "Setup git LFS"
description: "Setup git LFS and pull files stored with git-lfs."
runs:
  using: "composite"
  steps:
    - name: Create LFS file hash list
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .git/lfs-assets-id
      shell: bash

    - name: Restore LFS cache
      uses: actions/cache@v4
      with:
          path: .git/lfs
          key: lfs-${{ hashFiles('.git/lfs-assets-id') }}

    - name: Git LFS Pull
      run: git lfs pull
      shell: bash
