name: Documentation

on:
  push:
    branches:
      - main
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Restore pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-3.8

      - name: Upgrade pip and install pdm
        run: python -m pip install --upgrade pip pdm
        shell: bash

      - name: Restore PDM cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pdm
          key: pdm-cache-doc

      - name: Restore virtualenvs
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('pdm.lock') }}-doc

      - name: Poetry install
        run: pdm install --no-default --group docs
        shell: bash

      - name: Generate documentation
        run: pdm run mkdocs gh-deploy --force
